AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Fault Injection Simulator template


Resources:
  FiSRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - fis.amazonaws.com
          Action: sts:AssumeRole
          Condition:
            StringEquals:
              aws:SourceAccount: !Sub ${AWS::AccountId}
            ArnLike:
              aws:SourceArn: !Sub arn:aws:fis:${AWS::Region}:${AWS::AccountId}:experiment/*
  EC2Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: EC2FisPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Sid: AllowFISExperimentRoleEC2Actions
          Effect: Allow
          Action:
          - ec2:RebootInstances
          - ec2:StopInstances
          - ec2:StartInstances
          - ec2:TerminateInstances
          Resource: arn:aws:ec2:*:*:instance/*
        - Sid: AllowFISExperimentRoleSpotInstanceActions
          Effect: Allow
          Action:
          - ec2:SendSpotInstanceInterruptions
          Resource: arn:aws:ec2:*:*:instance/*
        - Sid: AllowFISExperimentRoleRDSReboot
          Effect: Allow
          Action:
          - rds:RebootDBInstance
          Resource: arn:aws:rds:*:*:db:*
        - Sid: AllowFISExperimentRoleRDSFailOver
          Effect: Allow
          Action:
          - rds:FailoverDBCluster
          Resource: arn:aws:rds:*:*:cluster:*
        - Effect: Allow
          Action:
          - logs:DescribeResourcePolicies
          - logs:DescribeLogGroups
          - logs:CreateLogDelivery
          Resource: '*'
        - Sid: AllowReadWriteToLogGroup
          Effect: Allow
          Action:
          - logs:PutLogEvents
          - logs:PutResourcePolicy
          Resource: !GetAtt LogGroup.Arn
      Roles:
      - !Ref FiSRole


  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: cf-ha-demo-logs

  ExperimentTemplate:
    Type: AWS::FIS::ExperimentTemplate
    Properties:
      Description: AutoScaleGroup automatically testing
      Actions:
        TerminateInstances:
          ActionId: aws:ec2:terminate-instances
          Targets:
            Instances: AppInstances
        RDSReboot:
          ActionId: aws:rds:reboot-db-instances
          Targets:
            DBInstances: DatabaseInstances
          Parameters:
            forceFailover: true
      Targets:
        AppInstances:
          SelectionMode: COUNT(1)
          ResourceType: 'aws:ec2:instance'
          ResourceTags:
            ENV: fis
        DatabaseInstances:
          SelectionMode: COUNT(1)
          ResourceType: 'aws:rds:db'
          ResourceTags:
            ENV: fis
      StopConditions:
        - Source: none
      RoleArn: !GetAtt FiSRole.Arn
      Tags:
        Key: Name
        Value: AutoScaleGroup EC2 FIS experience
      LogConfiguration:
        CloudWatchLogsConfiguration:
          LogGroupArn: !GetAtt LogGroup.Arn
        LogSchemaVersion: 1
    